In [1]:
import numpy as np

In [2]:
lspace=np.linspace(1,50,10)

In [3]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [4]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [5]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [6]:
listarray.dtype

dtype('int32')

In [7]:
listarray.shape

(3, 3)

In [8]:
listarray.size

9

In [9]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [10]:
zeros=np.zeros((2,5))

In [11]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
rng= np.arange(15)

In [14]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
lspace= np.linspace(1,10,5)

In [16]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
emp = np.empty((4,6))

In [18]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        6.23058707e-307, 8.45593934e-307, 7.56593017e-307],
       [1.11261027e-306, 1.11261502e-306, 1.42410839e-306,
        7.56597770e-307, 6.23059726e-307, 1.42419530e-306],
       [9.79101761e-307, 1.42417629e-306, 9.34603679e-307,
        1.78019761e-306, 1.78020848e-306, 7.56599807e-307],
       [1.42418172e-306, 2.04712906e-306, 7.56589622e-307,
        1.11258277e-307, 8.90111708e-307, 2.56765117e-312]])

In [19]:
emp_like = np.empty_like(lspace)

In [20]:
emp_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
ide = np.identity(10)

In [22]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
ide.shape

(10, 10)

In [24]:
arr= np.arange(99)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
arr = arr.ravel()

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.shape

(99,)

In [30]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [31]:
ar= np.array(x)

In [32]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [33]:
ar.sum()

29

In [34]:
ar.sum(axis=0)

array([12,  8,  9])

In [35]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [36]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [37]:
ar.flat

In [38]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [39]:
ar.ndim

2

In [40]:
ar.size

9

In [41]:
ar.nbytes

36

In [42]:
one = np.array([1,3,4,63,4,2])

In [43]:
one.argmax()

3

In [45]:
one.argmin()

0

In [46]:
one.argsort()

array([0, 5, 1, 2, 4, 3], dtype=int64)

In [47]:
ar2 = ar.T

In [48]:
ar + ar2

array([[ 2,  6, 10],
       [ 6, 10,  7],
       [10,  7,  0]])

In [49]:
ar * ar2

array([[ 1,  8, 21],
       [ 8, 25,  6],
       [21,  6,  0]])

In [50]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [51]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [53]:
np.count_nonzero(ar)

8

# 