In [1]:
import numpy as np

# Creating an array using numpy

In [2]:
#1-d array
food=np.array(['pakora','samosa','raita'])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
prices=np.array([5,5,5])
prices

array([5, 5, 5])

In [4]:
type(prices)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
prices[2]

5

In [7]:
food[2]

'raita'

In [8]:
len(prices)

3

In [10]:
prices.mean()

5.0

In [11]:
#zeros array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
#ones array
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
#empty array
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#specify
np.arange(3,20)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
#specify interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
#table
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
#line space
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
#specify your data type
np.ones(30,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [20]:
np.ones(30,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array function

In [23]:
a=np.array([12,30,40,34,65,75,44,0.6,.67,.3,100])
a

array([ 12.  ,  30.  ,  40.  ,  34.  ,  65.  ,  75.  ,  44.  ,   0.6 ,
         0.67,   0.3 , 100.  ])

In [25]:
a.sort()
a

array([  0.3 ,   0.6 ,   0.67,  12.  ,  30.  ,  34.  ,  40.  ,  44.  ,
        65.  ,  75.  , 100.  ])

In [26]:
b = np.array([21,43,45.5,44,.8,99,78,23,22])
b

array([21. , 43. , 45.5, 44. ,  0.8, 99. , 78. , 23. , 22. ])

In [27]:
c = np.concatenate((a,b))
c

array([  0.3 ,   0.6 ,   0.67,  12.  ,  30.  ,  34.  ,  40.  ,  44.  ,
        65.  ,  75.  , 100.  ,  21.  ,  43.  ,  45.5 ,  44.  ,   0.8 ,
        99.  ,  78.  ,  23.  ,  22.  ])

In [28]:
c.sort()
c

array([  0.3 ,   0.6 ,   0.67,   0.8 ,  12.  ,  21.  ,  22.  ,  23.  ,
        30.  ,  34.  ,  40.  ,  43.  ,  44.  ,  44.  ,  45.5 ,  65.  ,
        75.  ,  78.  ,  99.  , 100.  ])

# 2-D array


In [30]:
a=np.array([[1,2,3,4,5],
          [5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [31]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [38]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6]])

In [39]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6],
              [7,8]])

In [41]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [42]:
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [44]:
a = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [45]:
#to find dimension
a.ndim

3

In [46]:
#size (no of elements)
a.size

24

In [47]:
#shape
a.shape

(3, 2, 4)

In [51]:
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [52]:
x.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [53]:
x.shape

(6,)

In [56]:
np.reshape(a,newshape=(2,3),order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
#convert 1-D to 2-D array
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
#row wise 2-D conversion
b=a[np.newaxis,:]#convert into 2-D array
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
b.shape

(1, 9)

In [61]:
#column wise 2-D conversion
c=a[:,np.newaxis]#convert into 2-D array
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [62]:
#Array slicing
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a[2:6]

array([3, 4, 5, 6])

In [64]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [65]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [66]:
a.sum()

45

In [67]:
a.mean()

5.0